"  __     __    __  __ ____   ____
"  \ \   / /_ _|  \/  |  _ \ / ___|
"   \ \ / / | || |\/| | |_) | |
"    \ V /  | || |  | |  _ <| |___
"     \_/  |___|_|  |_|_| \_\\____|


"""""""""""""""""""""""""""""""""""""
               "PLUG
"""""""""""""""""""""""""""""""""""""

if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')

" Make Pretty
Plug 'Matt-Deacalion/vim-systemd-syntax'
Plug 'rafi/awesome-vim-colorschemes'
Plug 'flazz/vim-colorschemes'
Plug 'chriskempson/base16-vim'
Plug 'kien/rainbow_parentheses.vim'
Plug 'ryanoasis/vim-devicons'
Plug 'cj/vim-webdevicons'
Plug 'felixhummel/setcolors.vim'

""" Completion, Snippets and Linting
Plug 'w0rp/ale'
Plug 'maralla/completor.vim'
Plug 'ervandew/supertab'
Plug 'SirVer/ultisnips'
Plug 'honza/vim-snippets'
Plug 'Shougo/deoplete.nvim'
Plug 'roxma/nvim-yarp' " Supports deoplete
Plug 'roxma/vim-hug-neovim-rpc' " Supports deoplete in vim

""" Language Specific
Plug 'mattn/emmet-vim'
Plug 'pangloss/vim-javascript'
Plug 'arrufat/vala.vim'
Plug 'sheerun/vim-polyglot'

""" Coding Productivity
Plug 'tpope/vim-surround'
Plug 'majutsushi/tagbar'
Plug 'mbbill/undotree'
Plug 'airblade/vim-gitgutter'
Plug 'scrooloose/nerdcommenter'
Plug 'terryma/vim-multiple-cursors'
Plug 'mileszs/ack.vim'
Plug 'thinca/vim-quickrun'
Plug 'tpope/vim-eunuch'

""" Project Management
Plug 'xolox/vim-session'
Plug 'xolox/vim-misc'
Plug 'scrooloose/nerdtree'
Plug 'Xuyuanp/nerdtree-git-plugin'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'francoiscabrol/ranger.vim'

""" Status
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'

""" Tmux
Plug 'christoomey/vim-tmux-navigator'

call plug#end()

""""""""""""""""""""""""""""""""""""""
            "ARCHLABS
            "DEFAULTS
""""""""""""""""""""""""""""""""""""""

" A FEW SANE DEFAULTS FOR USE IN ARCHlABS

" load Arch Linux defaults
runtime! archlinux.vim

" yank text to system clipboard (requires +clipboard)
set clipboard^=unnamedplus

" enable line numbers
set number

" ask confirmation for certain things like when quitting before saving
set confirm

" enable tab completion menu when using colon command mode (:)
set wildmenu
set wildignore+=*/tmp/*,*.so,*.zip               " Linux
set wildignore+=*.pyc,*.out                      " Compiled files
set wildignore+=__pycache__						 " Py cache folder
set wildignore+=.hg,.git,.svn                    " Version control
set wildignore+=*.jpg,*.bmp,*.gif,*.png,*.jpeg   " binary images
set wildignore+=*.spl                            " compiled spelling word lists
set wildignore+=*.sw?                            " Vim swap files


set shortmess+=aAcIws   " Hide certain messages like 'Search Hit Bottom' etc.
set expandtab           " Tab inserts Spaces not Tabs '\t'
set softtabstop=4       " Amount of spaces to enter when Tab is pressed
set shiftwidth=4        " 4 space indentation
set tabstop=4
"set scrolloff=5         "show 5 lines above/below cursor
set showbreak=↪
set autochdir
set nohlsearch
set listchars=tab:▸\ ,eol:¬,extends:❯,precedes:❮
set matchpairs+=<:> "especially handy for html
set undofile " Maintain undo history
set undodir=~/.vim/undodir
set ignorecase " ignore case when searching
set smartcase
set gdefault "Always replace globally with s/this/that

" enable mouse, sgr is better but not every term supports it
set mouse=a
if has('mouse_sgr')
    set ttymouse=sgr
endif

" syntax highlighting with true colors in the terminal
syntax enable
if has('termguicolors')
    if &term =~? 'screen\|tmux'
        set t_8f=^[[38;2;%lu;%lu;%lum
        set t_8b=^[[48;2;%lu;%lu;%lum
    endif
    set termguicolors
endif

if filereadable(expand("~/.vimrc_background"))
  let base16colorspace=256
  source ~/.vimrc_background
endif


" bracketed paste while in insert mode, bracketed paste preserves indentation
inoremap <silent><C-v> <Esc>:set paste<CR>a<C-r>+<Esc>:set nopaste<CR>a

" better defaults
nnoremap 0 ^
nnoremap Y y$
nnoremap n nzzzv
nnoremap N Nzzzv
nnoremap <Tab> ==j
nnoremap g; g;zz

" better motions with wrapped text while preserving numbered jumps
for g:key in ['k', 'j', '<Up>', '<Down>']
    execute 'noremap <buffer> <silent> <expr> ' .
                \ g:key . ' v:count ? ''' .
                \ g:key . ''' : ''g' . g:key . ''''
    execute 'onoremap <silent> <expr> ' .
                \ g:key . ' v:count ? ''' .
                \ g:key . ''' : ''g' . g:key . ''''
endfor

augroup file_load_change_and_position
    " clear this group so they don't pile up
    autocmd!

    " when quitting, save position in file
    " when re-opening go to last position
    autocmd BufReadPost * call setpos(".", getpos("'\""))

    " Reload changes if file changed outside of vim
    " requires autoread (enabled by default)
    autocmd FocusGained,BufEnter * if mode() !=? 'c' | checktime | endif
    autocmd FileChangedShellPost * echo "Changes loaded from file"
augroup END

set tags=tags


"""""""""""""""""""""""""""""""""""""""
             " MORE
           " DEFAULTS
"""""""""""""""""""""""""""""""""""""""

set noswapfile

"""""""""""""""""""""""""""""""""""""""
           " VIM COLORS
"""""""""""""""""""""""""""""""""""""""

highlight SignColumn guibg=NONE
highlight SignColumn ctermbg=NONE
highlight TabLineFill guibg=#2C313C
highlight TabLineFill ctermbg=NONE
highlight TabLineFill ctermbg=NONE
highlight TabLineSel ctermbg=110
highlight TabLineSel ctermfg=NONE
highlight TabLine ctermbg=NONE
highlight TabLine ctermfg=NONE
highlight Visual ctermbg=124
highlight VertSplit guibg=NONE

let g:airline_theme='onedark'
colorscheme onedark

hi Normal guibg=NONE ctermbg=NONE
highlight VertSplit cterm=NONE

nnoremap <leader>ssl :colorscheme solarized8_light<CR> :AirlineTheme solarized<CR>
nnoremap <leader>ssd :colorscheme solarized8_dark<CR> :AirlineTheme base16_solarized<CR>
nnoremap <leader>shs :colorscheme base16-hopscotch<CR> :AirlineTheme base16<CR>

"""""""""""""""""""""""""""""""""""""""
           " LET THE GAMES BEGIN
"""""""""""""""""""""""""""""""""""""""

filetype plugin on

"""""""""""""""""""""""""""""""""""""""
           " VERSION CONTROL
"""""""""""""""""""""""""""""""""""""""

nnoremap <leader>cp :! clasp push<CR>


"""""""""""""""""""""""""""""""""""""""
           " SESSION MANAGEMENT
"""""""""""""""""""""""""""""""""""""""

let g:session_directory = "~/.vim/sessions"
let g:session_autoload = "no"
let g:session_autosave = "no"
let g:session_command_aliases = 1

nnoremap <leader>ss :SaveSession
nnoremap <leader>so :OpenSession
nnoremap <leader>sd :DeleteSession
nnoremap <leader>sc :CloseSession


"""""""""""""""""""""""""""""""""""""""
           " WINDOW MANAGEMENT
"""""""""""""""""""""""""""""""""""""""

"Split as you expect splits to split.
set splitright
set splitbelow

"split screen navigations
nnoremap <C-J> <C-W><C-J><cr>
nnoremap <C-K> <C-W><C-K><cr>
nnoremap <C-L> <C-W><C-L><cr>
nnoremap <C-H> <C-W><C-H><cr>

"Set leader key to spacebar. You know it makes sense
let mapleader = " "

" Open window in new tab (My preferred way to 'zoom' a window.)
nnoremap <leader>z :tabnew %<cr>

" make horizontal split full height
nnoremap <leader>ru <C-w><C-_>
" make vertical split full width
nnoremap <leader>rw <C-w>\|
" make split full screen (full width and height)
nnoremap <leader>rf <C-w><C-_><C-w>\|

" make splits equal size
nnoremap <leader>r= <C-w>=

" increase width by 5
nnoremap <leader>rl :vertical resize +5<cr>
" decrease width by 5
nnoremap <leader>rh :vertical resize -5<cr>
" increase height by 5
nnoremap <leader>rk :res +5<cr>
" decrease height by 5
nnoremap <leader>rj :res -5<cr>

" increase width by 1
nnoremap <leader>rL :vertical resize +1<cr>
" decrease width by 1
nnoremap <leader>rH :vertical resize -1<cr>
" increase height by 1
nnoremap <leader>rK :res +1<cr>
" decrease height by 1
nnoremap <leader>rJ :res -1<cr>

" resize for different widths
nnoremap <leader>r8 :vertical resize 80<cr>
nnoremap <leader>r9 :vertical resize 90<cr>
nnoremap <leader>r0 :vertical resize 100<cr>
nnoremap <leader>r1 :vertical resize 110<cr>
nnoremap <leader>r2 :vertical resize 120<cr>
nnoremap <leader>r3 :vertical resize 130<cr>
nnoremap <leader>r4 :vertical resize 140<cr>


"""""""""""""""""""""""""""""""""""""""
           " TAB MANAGEMENT
"""""""""""""""""""""""""""""""""""""""

nnoremap <leader>tl :tabnext<cr>
nnoremap <leader>th :tabnext<cr>


""""""""""""""""""""""""""""""""
           "NAVIGATION
""""""""""""""""""""""""""""""""

" Disable arrow keys
nnoremap <up> <nop>
nnoremap <down> <nop>
nnoremap <left> <nop>
nnoremap <right> <nop>
inoremap <up> <nop>
inoremap <down> <nop>
inoremap <left> <nop>
inoremap <right> <nop>

" j,k move by screen line instead of file line
nnoremap j gj
nnoremap k gk

""""""""""""""""""""""""""""""""
           "SAVE FOLDS
""""""""""""""""""""""""""""""""

"augroup remember_folds
  "autocmd!
  "autocmd BufWinLeave * mkview
  "autocmd BufWinEnter * silent! loadview
"augroup END

"""""""""""""""""""""""""""""""""""""""""""""""""
              "OPEN CONFIG FILES
                 "SHORTCUTS
"""""""""""""""""""""""""""""""""""""""""""""""""

"Use leader to source vimrc and ftplugins
nnoremap <leader>sv :source $MYVIMRC<cr>

" Open config files in vertical splits
nnoremap <leader>ev :vsplit ~/.vimrc<cr>
nnoremap <leader>ep :vsplit ~/.vim/after/ftplugin/python.vim<cr>
nnoremap <leader>ej :vsplit ~/.vim/after/ftplugin/javascript.vim<cr>
nnoremap <leader>eh :vsplit ~/.vim/after/ftplugin/html.vim<cr>
nnoremap <leader>ec :vsplit ~/.vim/after/ftplugin/css.vim<cr>
nnoremap <leader>ea :vsplit ~/.aliases<cr>
nnoremap <leader>eb :vsplit ~/.bashrc<cr>
nnoremap <leader>ez :vsplit ~/.zshrc<cr>
nnoremap <leader>ex :vsplit ~/.Xresources<cr>
nnoremap <leader>ei :vsplit ~/.config/i3/config<cr>
nnoremap <leader>eq :vsplit ~/.config/qutebrowser/qutebrowser.conf<cr>
nnoremap <leader>ei :vsplit ~/.config/termite/config<cr>
nnoremap <leader>em :vsplit ~/.tmux.conf<cr>
nnoremap <leader>et :vsplit ~/.config/alacritty/alacritty.yml<cr>


""""""""""""""""""""""""""""""""
          "INSERT MODE
          "TWEAKS
""""""""""""""""""""""""""""""""

" return in normal mode like return in insert mode
nnoremap <CR> a<CR>
nnoremap <Tab> i<space><space><space><space>

""""""""""""""""""""""""""""""""""""""
             "TOGGLE
            "SETTINGS
""""""""""""""""""""""""""""""""""""""

" Toggle spell check
nnoremap <leader>sp :setlocal spell! spelllang=en_us<CR>
nnoremap <leader>sl ]s
nnoremap <leader>sh [s
nnoremap <leader>sa zg
nnoremap <leader>sn z=

" Toggle relative or absolute number lines
nnoremap <leader>tn :call NumberToggle()<CR>

function! NumberToggle()
    if(&nu == 1)
        set nu!
        set rnu
    else
        set nornu
        set nu
    endif
endfunction


""""""""""""""""""""""""""""""""""""""
            "WHITE SPACE
""""""""""""""""""""""""""""""""""""""

" trim trailing whitespace on file save
fun! <SID>StripTrailingWhitespaces()
    let l = line(".")
    let c = col(".")
    %s/\s\+$//e
    call cursor(l, c)
endfun
autocmd BufWritePre * :call <SID>StripTrailingWhitespaces()

"convert tabs to spaces
:command! -range=% -nargs=0 Tab2Space execute '<line1>,<line2>s#^\t\+#\=repeat(" ", len(submatch(0))*' . &ts . ')'
"convert spaces to tab
:command! -range=% -nargs=0 Space2Tab execute '<line1>,<line2>s#^\( \{'.&ts.'\}\)\+#\=repeat("\t", len(submatch(0))/' . &ts . ')'

""""""""""""""""""""""""""""""""""""""
            "PLUGIN
            "SETTINGS
""""""""""""""""""""""""""""""""""""""
" Vim Sessions
set sessionoptions-=buffers
let g:session_autosave="yes"
let g:session_autosave_periodic=0

" Nerdtree
nnoremap <leader>nt :NERDTreeToggle<cr>
nnoremap <leader>nh :NERDTreeCWD<cr>
let g:NERDTreeWinSize=20
let NERDTreeMinimalUI = 1
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

" Ale custom colors and sign
highlight clear ALEErrorSign
let g:ale_fixers = {'javascript': ['prettier', 'eslint'], 'python': ['pylama'], 'vala': ['uncrustify']}

" Supertab scroll from top to bottom
"let g:SuperTabDefaultCompletionType = "<c-n>"

"DEOPLETE
let g:deoplete#enable_at_startup = 1
"let g:deoplete#omni#functions = {}
"let g:deoplete#omni#functions.javascript = [
  "\ 'tern#Complete',
  "\ 'jspc#omni'
"\]

" Change jedi default completions key bindings
let g:jedi#completions_command = "<C-N>"

" ULTISNIPS
let g:UltiSnipsExpandTrigger="<c-w>"
let g:UltiSnipsJumpForwardTrigger="<c-b>"
let g:UltiSnipsJumpBackwardTrigger="<c-z>"
let g:UltiSnipsListSnippets = "<C-l>"
let g:UltiSnipsEditSplit="vertical"

" TAGBAR
nnoremap <leader>tb :TagbarToggle<cr>
let g:tagbar_indent = 1
let g:tagbar_compact = 1
let g:tagbar_sort = 0
let g:tagbar_zoomwidth = 0
let g:tagbar_autoclose = 1

" UNDOTREE
nnoremap <leader>tu :UndotreeToggle<cr>

" VIMUX
nnoremap <Leader>vp :VimuxPromptCommand<CR>
nnoremap <Leader>j :VimuxRunLastCommand<CR>
nnoremap <Leader>c :VimuxInspectRunner<CR>

" TABOO
let g:taboo_tab_format = "%N~%f|"

" RAINBOWS
au Syntax * RainbowParenthesesLoadRound
au Syntax * RainbowParenthesesLoadSquare
au Syntax * RainbowParenthesesLoadBraces
nnoremap <Leader>tr :RainbowParenthesesToggle<cr>

" CTRL-P
let g:ctrlp_map = '<c-p>'
let g:ctrlp_cmd = 'CtrlPMixed'
nnoremap <Leader>pf :CtrlP<CR>
nnoremap <Leader>pb :CtrlPBuffer<CR>

" Use silver searcher with ack plugin
let g:ackprg = 'ag --nogroup --nocolor --column'
let g:quickrun_no_default_key_mappings=1

" QuickRun execution

inoremap <c-e> <esc>:w<cr> :QuickRun<cr>
nnoremap <c-e> :w<cr> :QuickRun<cr>

" NERDcommenter - Add space to comments
let NERDSpaceDelims=1

" JAVASCRIPT FOLDING / PANGLOSS PLUGIN
"augroup javascript_folding
    "au!
    "au FileType javascript setlocal foldmethod=syntax
"augroup END


""""""""""""""""""""""""""""""""""""""
            "ABBREVIATIONS
""""""""""""""""""""""""""""""""""""""

"iabbrev #bb #!/bin/bash
"iabbrev #bp #!/bin/env python
iabbrev DH Darren Haynes
iabbrev VH Veronica Haynes
iabbrev msgb Browser.msgBox();
iabbrev h1 <h1></h1><ESC>F<i
iabbrev h2 <h2></h2><ESC>F<i
iabbrev h3 <h3></h3><ESC>F<i
iabbrev h4 <h4></h4><ESC>F<i
iabbrev h5 <h5></h5><ESC>F<i

""""""""""""""""""""""""""""""""""""""
            "LINUXY
            "THINGS
""""""""""""""""""""""""""""""""""""""
nnoremap <leader>cw :! wc -w %:p<cr>
nnoremap <leader>cl :! wc -l %:p<cr>

" Complie and exec c file
nnoremap <Leader>mc :! gcc & ./a.out<cr>

""""""""""""""""""""""""""""""""""""""
             "NEOVIM
            "TERMINAL
""""""""""""""""""""""""""""""""""""""
nnoremap <leader><leader> :term<CR>
nnoremap <leader>j :split term://zsh<CR>
nnoremap <leader>\ :vsplit term://zsh<CR>
nnoremap <leader>t<leader> :tabnew term://zsh<CR>
tnoremap <C-b> <C-\><C-N>:b#<CR>
tnoremap <C-q> i<C-\><C-N>:q<CR>
tnoremap <C-k> <C-\><C-N><C-w>k<cr>
tnoremap <C-j> <C-\><C-N><C-w>j<cr>
tnoremap <C-h> <C-\><C-N><C-w>h<cr>
tnoremap <C-l> <C-\><C-N><C-w>l<cr>
tnoremap <C-7> <C-\><C-N>

nnoremap <leader>mn :term<CR>i%
function! CCompileWithFileName()
    let file = expand('%:r')
    let fullfile = expand('%:t')
    ":term<CR>
    "let job_id = b:terminal_job_id
    "echo job_id
endfunction

