#!/bin/sh
# Restore wallpaper
bash $HOME/.config/bspwm/.fehbg 

pgrep -x sxhkd > /dev/null || sxhkd &
# $HOME/.config/bspwm/polybar/launch.sh

bspc monitor -d '' '' '' '' '' ''

bspc config border_width         3
bspc config window_gap           10
bspc config split_ratio          0.50

bspc config focused_border_color "#414144"
bspc config normal_border_color "#1a1b26"
bspc config active_border_color "#1a1b26"

bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true

# fix pointer
xsetroot -cursor_name left_ptr

# workspaces
bspc rule -a qutebrowser desktop='^2' follow=on focus=on
bspc rule -a chromium desktop='^2' follow=on focus=on
bspc rule -a Thunar desktop='^3' follow=on focus=on
bspc rule -a discord desktop='^4'
bspc rule -a Gpick state=floating center=true
bspc rule -a Lxappearance state=floating center=true
bspc rule -a SpeedCrunch state=floating rectangle 300x400+0+0 center=true 

# Enable Super Keys For Menu
# ksuperkey -e 'Super_L=Alt_L|F1' &
# ksuperkey -e 'Super_R=Alt_L|F1' &

# polkit agent
if [[ ! `pidof polkit-gnome-authentication-agent-1` ]]; then
    /usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &
fi

# Launch keybindings daemon
sxhkd &

# Enable power management
xfce4-power-manager &

# start compositor
#while pgrep -u $UID -x compton >/dev/null; do sleep 1; done
# compton -b
picom --config $HOME/.config/bspwm/picom.conf
# replace neovim colorscheme
# sed -i "s/theme =.*$/theme = \"tokyonight\",/g" $HOME/.config/nvim/lua/custom/chadrc.lua 
# change xfce4-terminal colorscheme
XFCE_TERM_PATH="$HOME/.config/xfce4/terminal"
cp "$XFCE_TERM_PATH"/colorschemes/tokyo-night "$XFCE_TERM_PATH"/terminalrc

# change cava colorscheme
# CAVA_PATH="$HOME/.config/cava"
# cp "$CAVA_PATH"/colorschemes/tokyo-night "$CAVA_PATH"/config
