#!/bin/sh
# Restore wallpaper
bash "$HOME/.config/bspwm/.fehbg"

pgrep -x sxhkd >/dev/null || sxhkd &
# $HOME/.config/bspwm/polybar/launch.sh

bspc monitor -d '' '' '' '' '' ''

bspc config border_width 3
bspc config window_gap 10
bspc config split_ratio 0.50

bspc config focused_border_color "#83C092"
bspc config normal_border_color "#3D484D"
bspc config active_border_color "#FFFFFF"

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true

# fix pointer
xsetroot -cursor_name left_ptr

# workspaces
bspc rule -a qutebrowser desktop='^2' follow=on focus=on
bspc rule -a chromium desktop='^2' follow=on focus=on
bspc rule -a discord desktop='^3'
bspc rule -a Gpick state=floating rectangle 850x350+0+0 center=true
bspc rule -a Lxappearance state=floating center=true
bspc rule -a Arandr state=floating rectangle 850x850+0+0 center=true
bspc rule -a SpeedCrunch state=floating rectangle 300x400+0+0 center=true

# Autostart
if [[ ! $(pidof polkit-gnome-authentication-agent-1) ]]; then
  /usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &
fi
sxhkd &
xfce4-power-manager &
dunst -conf "$HOME/.config/dunst/dunstrc" &

# start compositor
#while pgrep -u $UID -x compton >/dev/null; do sleep 1; done
# compton -b
picom --config "$HOME/.config/bspwm/picom.conf"
