#!/bin/sh
bash "$HOME/.config/bspwm/.fehbg"

bspc monitor -d '' '' '' '' '' ''

bspc config border_width 3
bspc config window_gap 5
bspc config split_ratio 0.50

bspc config focused_border_color "#83C092"
bspc config normal_border_color "#3D484D"
bspc config active_border_color "#FFFFFF"

# When only 1 window open, no border
bspc config borderless_monocle true
# When only 1 window open, no gaps
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle true
bspc config focus_follows_pointer true

# fix pointer
xsetroot -cursor_name left_ptr

# workspaces
bspc rule -a qutebrowser desktop='^1' follow=on focus=on
bspc rule -a Chromium desktop='^3' follow=on focus=on
bspc rule -a discord desktop='^4' follow=on focus=on
bspc rule -a Gpick state=floating rectangle 850x350+0+0 center=true
bspc rule -a Lxappearance state=floating rectangle 850x450+0+0 center=true
bspc rule -a Arandr state=floating rectangle 850x850+0+0 center=true
bspc rule -a SpeedCrunch state=floating rectangle 300x400+0+0 center=true
bspc rule -a SimpleScreenRecorder state=floating rectangle 850x850+0+0 center=true
bspc rule -a Bitwarden state=floating rectangle 927x673+0+0 center=true
bspc rule -a my-electron-app state=floating
bspc rule -a feh state=floating

# Autostart
# if [ ! "$(pidof polkit-gnome-authentication-agent-1)" ]; then
#   /usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &
# fi
kill "$(pgrep -x sxhkd | awk 'NR==1 {print $0}')"
sxhkd &
xfce4-power-manager &
dunst -conf "$HOME/.config/dunst/dunstrc" &
dunstify --timeout=3000 --icon="$HOME/Dotfiles/icons/keyboard.png" "Sxhkd" "configuration reloaded"

# start compositor
#while pgrep -u $UID -x compton >/dev/null; do sleep 1; done
# compton -b
picom --config "$HOME/.config/bspwm/picom.conf"
