#!/bin/bash
printf " ____                                    ___              _          _  _ \n"
printf "| __ )  ___  _ __ __      __ _ __ ___   |_ _| _ __   ___ | |_  __ _ | || |\n"
printf "|  _ \ / __|| '_  \ /\ / /| '_ \` _ \   | | | '_ \ / __|| __|/ _\` || || |\n"
printf "| |_) |\__ \| |_) |\ V  V / | | | | | |  | | | | | |\__ \| |_| (_| || || |\n"
printf "|____/ |___/| .__/  \_/\_/  |_| |_| |_| |___||_| |_||___/ \__|\__,_||_||_|\n"
printf "            |_|                                                           \n"

source "$HOME/Dotfiles/install_scripts/utils.sh"
source "$HOME/Dotfiles/install_scripts/config.sh"
source "$HOME/Dotfiles/install_scripts/bspwm.sh"
source "$HOME/Dotfiles/install_scripts/apt-apps.sh"
source "$HOME/Dotfiles/install_scripts/fonts.sh"
source "$HOME/Dotfiles/install_scripts/oh-my-bash.sh"
source "$HOME/Dotfiles/install_scripts/wezterm.sh"
# source "$HOME/Dotfiles/install_scripts/chrome.sh"
# source "$HOME/Dotfiles/install_scripts/lf.sh"
source "$HOME/Dotfiles/install_scripts/MS-Fonts.sh"
source "$HOME/Dotfiles/install_scripts/printing.sh"
source "$HOME/Dotfiles/install_scripts/pyenv.sh"
source "$HOME/Dotfiles/install_scripts/pyenv_after.sh"
source "$HOME/Dotfiles/install_scripts/mupdf.sh"
source "$HOME/Dotfiles/install_scripts/rofi.sh"
source "$HOME/Dotfiles/install_scripts/browsers.sh"
source "$HOME/Dotfiles/install_scripts/neovim.sh"
source "$HOME/Dotfiles/install_scripts/neovim_after.sh"

printf " ___           _        _ _    ____                      _      _\n"
printf "|_ _|_ __  ___| |_ __ _| | |  / ___|___  _ __ ___  _ __ | | ___| |_ ___\n"
printf " | ||  _ \/ __| __/ _  | | | | |   / _ \|  _   _ \|  _ \| |/ _ \ __/ _ \\n"
printf " | || | | \__ \ || (_| | | | | |__| (_) | | | | | | |_) | |  __/ ||  __/\n"
printf "|___|_| |_|___/\__\__,_|_|_|  \____\___/|_| |_| |_| .__/|_|\___|\__\___|\n"
printf "                                                  |_|\n"
printf "\n"
