# if [[ -n $VIRTUAL_ENV && -e "${VIRTUAL_ENV}/bin/activate" ]]; then
  # source "${VIRTUAL_ENV}/bin/activate"
# fi

# export WORKON_HOME=$HOME/.virtualenvs


export EDITOR=nvim
export TERM=xterm-256color

# My scripts in dotfiles bin
export PATH=$PATH:$HOME/dotfiles/bin/

# Local bin path
export PATH=$HOME/.local/bin/:$PATH

# private bin path
export PATH=$HOME/.private_dotfiles/.bin:$PATH

# Base16 Shell
BASE16_SHELL="$HOME/.config/base16-shell/"
[ -n "$PS1" ] && \
    [ -s "$BASE16_SHELL/profile_helper.sh" ] && \
        eval "$("$BASE16_SHELL/profile_helper.sh")"

#Pyenv
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
export PYENV_VIRTUALENV_DISABLE_PROMPT=1
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi
